<?php 

function plotLayoutFullImageOrVideo() {

	return $fullImageOrVideo = [
		'key' => '5bbcd4f0b1aac',
		'name' => 'full-image-or-video',
		'label' => 'Full Image or Video',
		'display' => 'block',
		'sub_fields' => [
			[
				'key' => 'field_5e4d92e201630',
				'label' => 'Height',
				'name' => 'plotcms_height',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => 'plotAcfHalf',
					'id' => '',
				],
				'hide_admin' => 0,
				'choices' => [
					'small' => 'Small',
					'normal' => 'Normal',
					'large' => 'Large',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'normal',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			],
			[
				'key' => 'field_5e4d9ee434f03',
				'label' => 'Width',
				'name' => 'plotcms_width',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => 'plotAcfHalf',
					'id' => '',
				],
				'hide_admin' => 0,
				'choices' => [
					'fullWidth' => 'As wide as the screen allows',
					'maxWidth' => 'As wide as your site\'s maximum width',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'fullWidth',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			],
			[
				'key' => 'field_5e544dd58f798',
				'label' => 'Background Colour',
				'name' => 'plotcms_color_scheme',
				'type' => 'radio',
				'instructions' => 'This is the background colour beyond and around your full width image or video. Remember! Your colour palettes can be set in the site Customizer. 🐕',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5e4d9ee434f03',
							'operator' => '==',
							'value' => 'maxWidth',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'standard' => 'Site Background Colour',
					'alternative' => 'Alternative Background Colour',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'standard',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			],
			[
				'key' => 'field_5bbcd50ccefd9',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => 'Please add a title for this Plot segment. The title appears over the image or video. You can leave blank if you\'d like, if you don\'t want any text.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => 'plotAcfHalfWithoutFloat',
					'id' => '',
				],
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5eada3cec68ff',
				'label' => 'Include a paragraph?',
				'name' => 'include_a_paragraph',
				'type' => 'true_false',
				'instructions' => 'Include a small paragraph of text under your heading.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			],
			[
				'key' => 'field_5bbcd5bc40463',
				'label' => 'Paragraph',
				'name' => 'paragraph',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5eada3cec68ff',
							'operator' => '==',
							'value' => '1',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			],
			[
				'key' => 'field_5beab0ca69962',
				'label' => 'Background Type',
				'name' => 'background_type',
				'type' => 'radio',
				'instructions' => 'Please pick if this background should be an image, or a video.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'image' => 'Image',
					'video' => 'Video',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'image',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			],
			[
				'key' => 'field_5bbcd59c40462',
				'label' => 'Background Image',
				'name' => 'background_image',
				'type' => 'image',
				'instructions' => 'An image for your banner on large screens like desktops. Around 2,500px please.',
				'required' => 1,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5beab0ca69962',
							'operator' => '==',
							'value' => 'image',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => 'plotAcfHalf plotBlockLinkPreview--fullWidthImage plotAcfHalf--withClear plotBlockLinkPreview',
					'id' => '',
				],
				'hide_admin' => 0,
				'return_format' => 'array',
				'preview_size' => 'banner',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'field_5de2d532bbfb6',
				'label' => 'Small Screen Background Image',
				'name' => 'small_screen_background_image',
				'type' => 'image',
				'instructions' => 'An optional image for smaller screens like phones. Around 1,200px wide please.',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5beab0ca69962',
							'operator' => '==',
							'value' => 'image',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => 'plotAcfHalf plotBlockLinkPreview--fullWidthImage plotBlockLinkPreview',
					'id' => '',
				],
				'hide_admin' => 0,
				'return_format' => 'array',
				'preview_size' => 'banner--small-screen',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'field_5beab3ba69963',
				'label' => 'Background video',
				'name' => 'background_video',
				'type' => 'file',
				'instructions' => 'Upload an mp4 to use as a background video. Make sure it doesn\'t have audio! And also keep the filesize down by compressing for web. Smaller the better please 🙏',
				'required' => 1,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5beab0ca69962',
							'operator' => '==',
							'value' => 'video',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'url',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'mp4',
			],
			[
				'key' => 'field_5de2d57810dab',
				'label' => 'Small Screen Background Video',
				'name' => 'small_screen_background_video',
				'type' => 'file',
				'instructions' => 'An optional video to render for small screens. Can be 640px wide, smaller the better in file size to keep things great and fast to load. Otherwise it\'ll load the main video.',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5beab0ca69962',
							'operator' => '==',
							'value' => 'video',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'url',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'mp4',
			],
			[
				'key' => 'field_5c895cfe06534',
				'label' => 'Brightness',
				'name' => 'brightness',
				'type' => 'range',
				'instructions' => 'You might want to change the brightness of the background so that the text can be read over the top. 0 is completely transparent, and 100 is completely visible. Slide away 🍔',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => 'plotBlockLinkSlider plotBlockLinkSlider--fullWidthImage',
					'id' => '',
				],
				'hide_admin' => 0,
				'default_value' => 100,
				'min' => 0,
				'max' => 100,
				'step' => 1,
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'field_5e4d95f1fa1ad',
				'label' => 'Text Horizontal Alignment',
				'name' => 'plotcms_text_horizontal_alignment',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => 'plotAcfHalf plotAcfHalf--withClear',
					'id' => '',
				],
				'hide_admin' => 0,
				'choices' => [
					'left' => 'Left',
					'center' => 'Centre',
					'right' => 'Right',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'left',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			],
			[
				'key' => 'field_5e4d9699fa1ae',
				'label' => 'Text Vertical Alignment',
				'name' => 'plotcms_text_vertical_alignment',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => 'plotAcfHalf',
					'id' => '',
				],
				'hide_admin' => 0,
				'choices' => [
					'top' => 'Top',
					'middle' => 'Middle',
					'bottom' => 'Bottom',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'middle',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			],
			[
				'key' => 'field_5de2d4a099d35',
				'label' => 'Link Type',
				'name' => 'link_type',
				'type' => 'radio',
				'instructions' => 'You can give this section a link if you\'d like. Pick which type you\'d prefer.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'none' => 'No link',
					'button' => 'Users can click the button on screen to link through to a URL of your choice',
					'segment' => 'Users can click anywhere on this whole section to link through to a URL of your choice',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			],
			[
				'key' => 'field_5bbcd5ec40464',
				'label' => 'Add Button?',
				'name' => 'add_button',
				'type' => 'true_false',
				'instructions' => 'You can show a visible button on this too if you\'d like. It\'ll link to the same URL as clicking anywhere on the segment, but can help people better understand there\'s a link to follow.',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5de2d4a099d35',
							'operator' => '==',
							'value' => 'segment',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			],
			[
				'key' => 'field_5bbcd61640465',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => 'Words to appear on your lovely button.',
				'required' => 1,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5de2d4a099d35',
							'operator' => '==',
							'value' => 'button',
						],
					],
					[
						[
							'field' => 'field_5de2d4a099d35',
							'operator' => '==',
							'value' => 'segment',
						],
						[
							'field' => 'field_5bbcd5ec40464',
							'operator' => '==',
							'value' => '1',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5bbcd62740466',
				'label' => 'Link URL',
				'name' => 'link_url',
				'type' => 'text',
				'instructions' => 'Where do you want this link to head to when clicked? Paste in a URL of your choice.',
				'required' => 1,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5de2d4a099d35',
							'operator' => '==',
							'value' => 'segment',
						],
					],
					[
						[
							'field' => 'field_5de2d4a099d35',
							'operator' => '==',
							'value' => 'button',
						],
						[
							'field' => 'field_5bbcd5ec40464',
							'operator' => '==',
							'value' => '1',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5de2db00c59fe',
				'label' => 'Open in a new tab?',
				'name' => 'open_in_new_tab',
				'type' => 'true_false',
				'instructions' => 'Check this if you want the link to open in a new tab.',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5de2d4a099d35',
							'operator' => '!=',
							'value' => 'none',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			],
		],
		'min' => '',
		'max' => '',
	];
}