<?php

acf_add_local_field_group([
	'key' => 'group_5e14d14e99cc6',
	'title' => 'Artists Page Options',
	'fields' => [
		[
			'key' => 'field_5e14d154fc921',
			'label' => 'Allow Artist Type Filters',
			'name' => 'allow_artist_type_filters',
			'type' => 'true_false',
			'instructions' => 'If you\'d like to display a list of artist types that can filter your A-Z of artists, tick this chap. 🙏',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e67e41f67dd3',
			'label' => 'Allow Day Filters',
			'name' => 'allow_day_filters',
			'type' => 'true_false',
			'instructions' => 'Buttons that break down your artist list by the days they\'re performing on. Requires you to populate the "performances" area. 🎰',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e67e45c67dd4',
			'label' => 'Desktop rows',
			'name' => 'desktop_rows',
			'type' => 'radio',
			'instructions' => 'How many artists do you want to display per row on desktop? On phones we\'ll stack one by one anyway.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				3 => 'Three per row',
				4 => 'Four per row',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 3,
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5ea027d9cc8a0',
			'label' => 'All Categories Button Text',
			'name' => 'all_categories_button_text',
			'type' => 'text',
			'instructions' => 'Text to use on your button to display all categories of artists.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => 'All',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 10,
		],
		[
			'key' => 'field_5e67e625e4f73',
			'label' => 'No Results Message',
			'name' => 'no_results_message',
			'type' => 'text',
			'instructions' => 'Message to show your visitors if they manage to hit a combination of filters resulting in no results. Not likely to happen- but could!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 'No artists found :( Please try a different search.',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
	],
	'location' => [
		[
			[
				'param' => 'page',
				'operator' => '==',
				'value' => '409',
			],
		],
	],
	'menu_order' => 19,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Specific options and fields for the artist page',
]);