<?php 


acf_add_local_field_group([
	'key' => 'group_5e64cb7f07af7',
	'title' => 'Event Settings',
	'fields' => [
		[
			'key' 			=> 'event_settings_display_performance_dates',
			'label' 		=> 'Display performance dates',
			'name' 			=> 'display_performance_dates',
			'type' 			=> 'select',
			'instructions' 	=> 'How dates are displayed on the site, on artist, schedule and performance pages.',
			'required' 		=> 1,
			'choices' 		=> [
				'l' 			=> 'Just the day (eg. Sunday)',
				'dS M' 			=> '31st Jul',
				'M dS' 			=> 'Jul 31st',
				'd/m/y' 		=> '31/01/22',
				'm/d/y' 		=> '01/31/22'
			],
			'default_value' => 'l'
		],
		[
			'key' 			=> 'event_settings_date_picker',
			'label' 		=> 'Date Picker Type',
			'name' 			=> 'date_picker_type',
			'type' 			=> 'select',
			'instructions' 	=> 'Date pickers for the artists or performance pages.',
			'required' 		=> 1,
			'choices' 		=> [
				'select' 			=> 'Simple dropdown of all dates',
				'calendar' 			=> 'Calendar picker'
			],
			'default_value' => 'select'
		],
		[
			'key' 			=> 'event_settings_day_end',
			'label' 		=> 'When does a day end?',
			'name' 			=> 'day_end',
			'type' 			=> 'range',
			'instructions' 	=> 'Sometimes you want a show on, for example, 4am on a Saturday morning, to show up on your Friday night billing. Here you can slide when the end of day is according to your schedule.',
			'default_value' => 100,
			'min' 			=> 0,
			'max' 			=> 8,
			'step' 			=> 1,
			'append' 		=> ':00am'
		],
		[
			'key' => 'field_5e945eeb916fc',
			'label' => 'Event Type',
			'name' => 'event_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'stage-based' => 'Single location with one or more stages',
				'location-based' => 'Across multiple locations or venues',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e8f0e0e5f355',
			'label' => 'Allow Stages to have their own pages',
			'name' => 'stage_pages',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e8f0e285f356',
			'label' => 'Allow performances to have their own pages',
			'name' => 'performance_pages',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e917dbee610a',
			'label' => 'Performance Links',
			'name' => 'performance_links',
			'type' => 'radio',
			'instructions' => 'On stage and schedule pages, you can decide where you want your title to link through to.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'artist' => 'Performances link through to artist biogs',
				'performance' => 'Performances link through to their performance pages',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'artist',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5ea012d2f9d4e',
			'label' => 'Artist Links',
			'name' => 'artist_links',
			'type' => 'radio',
			'instructions' => 'You can either have artist biogs pop up in modals, or head to a dedicated page on the site.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'off' => 'Open artist biogs in new page',
				'side' => 'Modal popup slides in from the side',
				'central' => 'Modal popup appears in the centre of the screen',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'side',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5ea17a4614359',
			'label' => 'Show article dates',
			'name' => 'show_article_dates',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5ea17a581435a',
			'label' => 'Show article authors',
			'name' => 'show_article_authors',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
	],
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'event-settings',
			],
		],
	],
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
]);