<?php 

require_once('partners.php');
require_once('404.php');
require_once('event-settings.php');
require_once('stage-page-content.php');
require_once('performance-info.php');
require_once('tracking-scripts.php');
require_once('banner.php');
require_once('sub-menu.php');
require_once('sub-menu-options.php');
require_once('performances.php');
require_once('tickets.php');
require_once('schedule-page.php');
require_once('artist-information.php');
require_once('stage-listing-information.php');
require_once('performance-listing-information.php');
require_once('stages.php');

require_once('plot-layouts.php');

require_once('artist-page.php');
require_once('news.php');
require_once('whats-on.php');
require_once('past-performances.php');
require_once('past-artists.php');
require_once('search-engines-and-social.php');
require_once('domains.php');
require_once('ssl.php');


acf_add_local_field_group([
	'key' => 'group_5e204ef2995d1',
	'title' => 'Lineup Poster',
	'fields' => [
		[
			'key' => 'field_5e204ef85fd1f',
			'label' => 'Lineup Poster',
			'name' => 'lineup_poster',
			'type' => 'image',
			'instructions' => 'Upload your lineup poster. As big as possible, but 2000px minimum width should be great.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'small',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5e204f195fd20',
			'label' => 'Small Screen Lineup Poster',
			'name' => 'small_screen_lineup_poster',
			'type' => 'image',
			'instructions' => 'A small screen alternate for the lineup poster. 1500px wide please.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'small',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
	],
	'location' => [
		[
			[
				'param' => 'page',
				'operator' => '==',
				'value' => '1119',
			],
		],
	],
	'menu_order' => 18,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
]);


acf_add_local_field_group([
	'key' => 'group_5e1c412b3fd3f',
	'title' => 'Artist Social Links',
	'fields' => [
		[
			'key' => 'field_5e9f065444f13',
			'label' => 'Social Links',
			'name' => 'social_links',
			'type' => 'repeater',
			'instructions' => 'Pick as many social links as you\'d like. This will put links on your artist biog pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => [
				[
					'key' => 'field_5e9f067844f14',
					'label' => 'Social Network',
					'name' => 'social_network',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'choices' => [
						'youtube' => 'Youtube',
						'spotify' => 'Spotify',
						'soundcloud' => 'Soundcloud',
						'bandcamp' => 'Bandcamp',
						'facebook' => 'Facebook',
						'twitter' => 'Twitter',
						'instagram' => 'Instagram',
					],
					'default_value' => [
					],
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'array',
					'ajax' => 0,
					'placeholder' => '',
				],
				[
					'key' => 'field_5e9f0716fad0d',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'url',
					'instructions' => 'Paste in the social media account URL 🥇',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => '',
					'placeholder' => '',
				],
			],
		],
	],
	'location' => [
		[
			[
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'artist',
			],
		],
	],
	'menu_order' => 20,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Links for external social media for artists.',
]);

acf_add_local_field_group([
	'key' => 'group_5bc842383992e',
	'title' => 'Site Status',
	'fields' => [
		[
			'key' => 'field_5bc842446f67f',
			'label' => 'Site Status',
			'name' => 'site_status',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'live' => 'Website is live',
				'hidden' => 'Website is hidden from the public. Holding page is displayed only',
				'splash' => 'Holding page acts as a splash screen. Users can click through to view website',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' 					=> 'plot_site_status_full_site_text',
			'label' 				=> 'Link text for viewing the whole site',
			'name'					=> 'view_whole_site_link_text',
			'instructions' 			=> 'Text that appears at the bottom of the holding page that links through to the home page.',
			'type'					=> 'text',
			'required'				=> true,
			'conditional_logic'		=> [
					[
						[
							'field' 		=> 'field_5bc842446f67f',
							'value' 		=> 'splash',
							'operator' 		=> '=='
						]
					]
				],
			'default_value' 		=> 'View full site'
		],
		[
			'key' => 'field_5bc842976f680',
			'label' => 'Holding Page',
			'name' => 'holding_page',
			'type' => 'post_object',
			'instructions' => 'Pick a page to divert users to when the site is not live. This will be ignored if the above checkbox is checked.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5bc842446f67f',
						'operator' => '==',
						'value' => 'hidden',
					],
				],
				[
					[
						'field' => 'field_5bc842446f67f',
						'operator' => '==',
						'value' => 'splash',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'post_type' => [
				0 => 'holding-page',
			],
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		],
	],
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'site-status',
			],
		],
	],
	'menu_order' => 21,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Is the site live or not? Which holding page to show?',
]);

acf_add_local_field_group([
	'key' => 'group_5bc82e6c719e1',
	'title' => 'Holding Pages',
	'fields' => [
		[
			'key' => 'field_5e1c688b8d77d',
			'label' => 'Background Type',
			'name' => 'background_type',
			'type' => 'radio',
			'instructions' => 'Your background can have an image or a video full screen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'image' => 'Image',
				'video' => 'Video',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e1c68e08d77e',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => 'This image should be around 2500 pixels wide to make sure it looks great on big desktop screens. It will automatically compress and resize to be perfect for web.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1c688b8d77d',
						'operator' => '==',
						'value' => 'image',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5e1c69138d77f',
			'label' => 'Small Screen Background Image',
			'name' => 'small_screen_background_image',
			'type' => 'image',
			'instructions' => 'An optional image for smaller screens like phones. Good if you want an alternate crop on smaller screens. Can be 1200px wide. If left blank we\'ll just deliver the larger image, scaled down in size.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1c688b8d77d',
						'operator' => '==',
						'value' => 'image',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5e1c692e8d780',
			'label' => 'Background Video',
			'name' => 'background_video',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1c688b8d77d',
						'operator' => '==',
						'value' => 'video',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		],
		[
			'key' => 'field_5e1c695a8d781',
			'label' => 'Small screen Background Video',
			'name' => 'small_screen_background_video',
			'type' => 'file',
			'instructions' => 'An optional video to render for small screens. Can be 640px wide, smaller the better in file size to keep things great and fast to load. Otherwise it\'ll load the main video.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1c688b8d77d',
						'operator' => '==',
						'value' => 'video',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		],
		[
			'key' => 'field_5e836ec39cb5f',
			'label' => 'Background Brightness',
			'name' => 'background_brightness',
			'type' => 'range',
			'instructions' => 'You can slide the brightness down if your image or video is too bright.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 100,
			'min' => 0,
			'max' => 100,
			'step' => 1,
			'prepend' => '',
			'append' => '',
		],
		[
			'key' => 'field_5e8367d63a097',
			'label' => 'Include a logo?',
			'name' => 'include_a_logo',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e83682d3a098',
			'label' => 'Logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => 'This will look best as a png with a transparent background, at least 1000px wide.',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e8367d63a097',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5e83708eecbec',
			'label' => 'Include a heading?',
			'name' => 'include_a_heading',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5bc82e7106a8e',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'A short heading for this holding page.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e83708eecbec',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e8369023a099',
			'label' => 'Include a statement?',
			'name' => 'include_a_statement',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5bc82e8706a8f',
			'label' => 'Statement',
			'name' => 'statement',
			'type' => 'wysiwyg',
			'instructions' => 'An optional statement to go on this holding page.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e8369023a099',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5e1c683c53dec',
			'label' => 'Include a form?',
			'name' => 'include_a_form',
			'type' => 'true_false',
			'instructions' => 'Would you like to include a sign up form?',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1c688b8d77d',
						'operator' => '!=empty',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e835d0307af1',
			'label' => 'Form',
			'name' => 'form',
			'type' => 'post_object',
			'instructions' => 'Pick a form to include if you\'d like. Usually your typical email sign up form is good for here.',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1c683c53dec',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'post_type' => [
				0 => 'wpforms',
			],
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		],
		[
			'key' => 'field_5e836b9cd7d30',
			'label' => 'Include Social Media Links',
			'name' => 'include_social_media_links',
			'type' => 'true_false',
			'instructions' => 'You can modify your social media links settings under "social media".',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
	],
	'location' => [
		[
			[
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'holding-page',
			],
		],
	],
	'menu_order' => 22,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => [
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	],
	'active' => true,
	'description' => 'Fields for any holding pages on the site',
]);

acf_add_local_field_group([
	'key' => 'group_5bbcd437f3682',
	'title' => 'Notifications',
	'fields' => [
		[
			'key' => 'field_5c88f8c9693d3',
			'label' => 'Disabled',
			'name' => 'disabled',
			'type' => 'true_false',
			'instructions' => 'Disable me if you want to turn me off! 🙌',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5c87d7fe7e520',
			'label' => 'Notification Type',
			'name' => 'notification_type',
			'type' => 'radio',
			'instructions' => 'Banners appear at the top of pages. Popups appear as a modal in front of everything. Popups can have images and buttons, banners are for shorter messages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'Pop Up' => 'Pop Up',
				'Banner' => 'Banner',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e8dd6531f24a',
			'label' => 'Animation',
			'name' => 'animation',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d7fe7e520',
						'operator' => '==',
						'value' => 'Banner',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'always' => 'Always animate from left to right',
				'maybe' => 'Only animate from left to right if there\'s not enough space for the wording on the screen',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5c88f84717973',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => 'A featured image for the popup. Make sure it\'s at least 1500px wide.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d7fe7e520',
						'operator' => '==',
						'value' => 'Pop Up',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5bbcd43d7a239',
			'label' => 'Message',
			'name' => 'message',
			'type' => 'wysiwyg',
			'instructions' => 'What message would you like this notification to say?',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d7fe7e520',
						'operator' => '==',
						'value' => 'Pop Up',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5e8dd52860749',
			'label' => 'Message',
			'name' => 'message_for_banner',
			'type' => 'text',
			'instructions' => 'What message would you like this notification to say?',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d7fe7e520',
						'operator' => '==',
						'value' => 'Banner',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e8def2971aff',
			'label' => 'Banner Link',
			'name' => 'banner_link',
			'type' => 'text',
			'instructions' => 'If you\'d like the banner to link somewhere, paste a link in here. Otherwise you can just leave it blank.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d7fe7e520',
						'operator' => '==',
						'value' => 'Banner',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5c88f86717974',
			'label' => 'Show Button?',
			'name' => 'show_button',
			'type' => 'true_false',
			'instructions' => 'If you would like a link button on this popup, please tick.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d7fe7e520',
						'operator' => '==',
						'value' => 'Pop Up',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5c88f89117975',
			'label' => 'URL',
			'name' => 'url',
			'type' => 'text',
			'instructions' => 'Where do you want this button to link to?',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c88f86717974',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5c88f8a317976',
			'label' => 'Button Text',
			'name' => 'button_text',
			'type' => 'text',
			'instructions' => 'What message do you want to write on the button?',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c88f86717974',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e1cda7112d91',
			'label' => 'Show notification within a specific time frame?',
			'name' => 'show_notification_within_a_specific_time_frame',
			'type' => 'true_false',
			'instructions' => 'Check if you want to pick a date and time range for this notification.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5bbcd46a7a23b',
			'label' => 'Date from',
			'name' => 'date_from',
			'type' => 'date_time_picker',
			'instructions' => 'When should this notification appear?',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1cda7112d91',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'd/m/Y g:i a',
			'first_day' => 1,
		],
		[
			'key' => 'field_5bbcd4807a23c',
			'label' => 'Date to',
			'name' => 'date_to',
			'type' => 'date_time_picker',
			'instructions' => 'When should this notification expire?',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1cda7112d91',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'd/m/Y g:i a',
			'first_day' => 1,
		],
		[
			'key' => 'field_5c87d9307e521',
			'label' => 'Time until popup shows',
			'name' => 'time_until_popup_shows',
			'type' => 'number',
			'instructions' => 'Time in seconds until the popup arrives on screen for your visitors.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d7fe7e520',
						'operator' => '==',
						'value' => 'Pop Up',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		],
		[
			'key' => 'field_5c87d9617e522',
			'label' => 'Display Options',
			'name' => 'display_options',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'exclude' => 'Show on all pages, apart from certain pages that I pick',
				'include' => 'Let me pick specifically which pages it should show on',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5c87d9a87e523',
			'label' => 'Which pages?',
			'name' => 'which_pages',
			'type' => 'post_object',
			'instructions' => 'Which pages do you want this notification to show on?',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d9617e522',
						'operator' => '==',
						'value' => 'include',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'post_type' => [
				0 => 'page',
				1 => 'post',
				2 => 'stage',
				3 => 'holding-page',
			],
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		],
		[
			'key' => 'field_5e1db797a236d',
			'label' => 'Exclude these pages',
			'name' => 'exclude_these_pages',
			'type' => 'post_object',
			'instructions' => 'If you\'d like to pick a page to not show the notification on, you can. 🧑🏻‍✈️',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5c87d9617e522',
						'operator' => '==',
						'value' => 'exclude',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'post_type' => [
				0 => 'page',
				1 => 'post',
				2 => 'holding-page',
				3 => 'stage',
			],
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		],
	],
	'location' => [
		[
			[
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'notification',
			],
		],
	],
	'menu_order' => 24,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => [
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	],
	'active' => true,
	'description' => 'Options for notification popups and banners',
]);

acf_add_local_field_group([
	'key' => 'group_5e468a5059a44',
	'title' => 'Partners',
	'fields' => [
		[
			'key' => 'field_5e468a5496f56',
			'label' => 'Logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => 'Please upload a png with a transparent background for these if possible, so they blend with the site better. At least 300px wide.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5e468a8796f57',
			'label' => 'Link',
			'name' => 'link',
			'type' => 'text',
			'instructions' => 'Paste in a URL if you want this logo to be clickable. If you leave it blank, it won\'t be clickable.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
	],
	'location' => [
		[
			[
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'partner',
			],
		],
	],
	'menu_order' => 25,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => [
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	],
	'active' => true,
	'description' => '',
]);

acf_add_local_field_group([
	'key' => 'group_5bbcc4d920730',
	'title' => 'FAQs',
	'fields' => [
		[
			'key' => 'field_5bbcc4ddb6742',
			'label' => 'Answer',
			'name' => 'answer',
			'type' => 'wysiwyg',
			'instructions' => 'Please add the answer to this frequently asked question below:',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		],
	],
	'location' => [
		[
			[
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'faq',
			],
		],
	],
	'menu_order' => 26,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => [
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	],
	'active' => true,
	'description' => 'FAQ options',
]);

acf_add_local_field_group([
	'key' => 'group_5c8a660896286',
	'title' => 'Footer',
	'fields' => [
		[
			'key' => 'field_5e54fdaa42af9',
			'label' => 'Footer Logo',
			'name' => 'footer_logo',
			'type' => 'image',
			'instructions' => 'This will default to use the main logo for your event. But sometimes that doesn\'t look so nice in the footer, so you can override, with maybe a white out or monochrome version. If you leave blank, it\'ll use the main one.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5e4d61bd27dae',
			'label' => 'Include a message in the footer?',
			'name' => 'include_a_message_in_the_footer',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e1e2b2889110',
			'label' => 'Footer Message',
			'name' => 'footer_message',
			'type' => 'textarea',
			'instructions' => 'A custom optional message to appear in the footer on all pages.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e4d61bd27dae',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		],
		[
			'key' => 'field_5e47d9fa1ef57',
			'label' => 'Include newsletter signup',
			'name' => 'footer_include_newsletter_signup',
			'type' => 'true_false',
			'instructions' => 'Would you like a newsletter sign up form to appear in the footer on all pages?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e8b4567748d7',
			'label' => 'Form Style',
			'name' => 'plotcms_footer_form_style',
			'type' => 'radio',
			'instructions' => 'Your form colour and style options can be set in the customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Main Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'alternative',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e47da641ef58',
			'label' => 'Newsletter Text',
			'name' => 'footer_newsletter_text',
			'type' => 'text',
			'instructions' => 'Useful text to explain the newsletter sign up form in the footer',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e47d9fa1ef57',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => 'Sign up to our newsletter',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e4d62ac96e57',
			'label' => 'Include Footer Navigation?',
			'name' => 'include_footer_navigation',
			'type' => 'true_false',
			'instructions' => 'Your footer navigation items can be set within the "menus" section of the admin. 🧭',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
	],
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'footer',
			],
		],
	],
	'menu_order' => 27,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => [
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	],
	'active' => true,
	'description' => 'Just some footer features',
]);

acf_add_local_field_group([
	'key' => 'group_5befe70b827ca',
	'title' => 'Tickets Button',
	'fields' => [
		[
			'key' => 'field_5e1e29d40ba45',
			'label' => 'Show main tickets button',
			'name' => 'show_main_tickets_button',
			'type' => 'true_false',
			'instructions' => 'The main tickets button appears fixed to the bottom on all pages on phones, and in the header on all pages on desktop. Check this if you want to include this.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5befe7132cd68',
			'label' => 'Main Tickets Button Text',
			'name' => 'main_tickets_button_text',
			'type' => 'text',
			'instructions' => 'The wording for your ticket button. For example, "BUY NOW - from £39.99"',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1e29d40ba45',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5befe7242cd69',
			'label' => 'Main Tickets Button Link',
			'name' => 'main_tickets_button_link',
			'type' => 'url',
			'instructions' => 'A link to where you would like this main button to head. This can either be straight to your ticket provider, or over to your own tickets page. 🚤',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1e29d40ba45',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
		],
		[
			'key' => 'field_5e1e2a8b0ba47',
			'label' => 'Exclude Main Tickets Button',
			'name' => 'exclude_main_tickets_button',
			'type' => 'post_object',
			'instructions' => 'Want to hide the Main Tickets Button on certain pages? Slap them in here.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e1e29d40ba45',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'post_type' => [
				0 => 'post',
				1 => 'page',
				2 => 'stage',
			],
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		],
	],
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'big-tickets-button',
			],
		],
	],
	'menu_order' => 28,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Options for the big ticket button that typically appears sitewide',
]);

acf_add_local_field_group([
	'key' => 'group_5befe74acf6c5',
	'title' => 'Social Media',
	'fields' => [
		[
			'key' => 'field_5e9f2182532c4',
			'label' => 'Social Links',
			'name' => 'social_links',
			'type' => 'repeater',
			'instructions' => 'Pick as many social links as you\'d like. They\'ll be available to use in the footer and on your holding pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add new social link',
			'sub_fields' => [
				[
					'key' => 'field_5e9f21b3532c5',
					'label' => 'Social Network',
					'name' => 'social_network',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'choices' => [
						'youtube' => 'Youtube',
						'spotify' => 'Spotify',
						'soundcloud' => 'Soundcloud',
						'bandcamp' => 'Bandcamp',
						'facebook' => 'Facebook',
						'twitter' => 'Twitter',
						'instagram' => 'Instagram',
					],
					'default_value' => [
					],
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'array',
					'ajax' => 0,
					'placeholder' => '',
				],
				[
					'key' => 'field_5e9f21c8532c6',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => '',
					'placeholder' => '',
				],
			],
		],
	],
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'social-media',
			],
		],
	],
	'menu_order' => 29,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Social Media links that are typically sitewide, aka in the footer',
]);

