<?php 

if(get_field('performance_pages','option')) :

	acf_add_local_field_group([
		'key' => 'group_5e9c87277fb25',
		'title' => 'Page Options',
		'fields' => [
			[
				'key' => 'field_5e9c874c07401',
				'label' => 'Individual tickets?',
				'name' => 'individual_tickets',
				'type' => 'true_false',
				'instructions' => 'Check this box if you can buy individual tickets for this. It will add a specific ticket button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			],
			[
				'key' => 'field_5ea07114a455b',
				'label' => 'Prices',
				'name' => 'prices',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5e9c874c07401',
							'operator' => '==',
							'value' => '1',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add ticket',
				'sub_fields' => [
					[
						'key' => 'field_5ea071e0a455c',
						'label' => 'Ticket title',
						'name' => 'ticket_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'hide_admin' => 0,
						'default_value' => '',
						'placeholder' => 'General admission',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5ea07209a455d',
						'label' => 'Price',
						'name' => 'price',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'hide_admin' => 0,
						'default_value' => '',
						'placeholder' => '£15.00',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
				],
			],
			[
				'key' => 'field_5e9c89fbf1796',
				'label' => 'Link URL',
				'name' => 'link_url',
				'type' => 'text',
				'instructions' => 'Where do you want your ticket button to link to?',
				'required' => 1,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5e9c874c07401',
							'operator' => '==',
							'value' => '1',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5e9c8a64f1797',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => 'The text for the button itself',
				'required' => 1,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5e9c874c07401',
							'operator' => '==',
							'value' => '1',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'default_value' => 'Buy Tickets',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5ea0726344058',
				'label' => 'Sold out?',
				'name' => 'sold_out',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => [
					[
						[
							'field' => 'field_5e9c874c07401',
							'operator' => '==',
							'value' => '1',
						],
					],
				],
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			],
			[
				'key' => 'field_5e9c87e907402',
				'label' => 'Show stage information',
				'name' => 'show_stage_information',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			],
			[
				'key' => 'field_5e9c882407403',
				'label' => 'Additional information',
				'name' => 'additional_information',
				'type' => 'repeater',
				'instructions' => 'Add in optional information of any type to appear in your info panel.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => [
					[
						'key' => 'field_5e9c886d07404',
						'label' => 'Info title',
						'name' => 'info_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'hide_admin' => 0,
						'default_value' => '',
						'placeholder' => 'eg. Suitable for',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5e9c88b907405',
						'label' => 'Info',
						'name' => 'info',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'hide_admin' => 0,
						'default_value' => 'Over 15s',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
				],
			],
			[
				'key' => 'field_5e9c872a07400',
				'label' => 'Content',
				'name' => 'content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			],
		],
		'location' => [
			[
				[
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'performance',
				],
			],
		],
		'menu_order' => 13,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	]);

endif;