<?php 

$locations = [
	[
		[
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'page',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '409',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '919',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '393',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '904',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '992',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '1119',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '3828',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '3834',
		],
		[
			'param' => 'page',
			'operator' => '!=',
			'value' => '3878',
		]
	],
	[
		[
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'post',
		],
	]
];


//If stage pages are public, show here too.
if(get_field('stage_pages','option')) :

	$locations[] = [
		[
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'stage',
		],
	];

endif;

//If performance pages are public, show here too.
if(get_field('performance_pages','option')) :

	$locations[] = [
		[
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'performance',
		],
	];

endif;

require_once('plot-layouts/full-image-or-video.php');
require_once('plot-layouts/featured-performances.php');

$layouts = [];

$layouts['5bbcd4f0b1aac'] = plotLayoutFullImageOrVideo();
$layouts['5bc82ff108569'] = [
	'key' => '5bc82ff108569',
	'name' => 'fluid-content',
	'label' => 'Fluid Content',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e52cc60e41f3',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5bc830270856b',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'You can leave this blank if you don\'t want a heading.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5bc830120856a',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		],
	],
	'min' => '',
	'max' => '',
];
$layouts['5bc82c88de3ea'] = [
	'key' => '5bc82c88de3ea',
	'name' => 'fifty-fifty',
	'label' => 'Fifty Fifty',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e5284431a4eb',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'plotAcfHalf',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5bc82c9cde3eb',
			'label' => 'Layout option',
			'name' => 'layout_option',
			'type' => 'radio',
			'instructions' => 'On desktop, you can have an image on the left of your text, or to the right. On phone screens, images will appear above your content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'plotAcfHalf',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'left' => 'Image on left (on desktop]',
				'right' => 'Image on right (on desktop]',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'left',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5bc82ce0de3ec',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'If you don\'t want a heading for this segment, you can leave blank.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5bc82cebde3ed',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5beedf4a23d52',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => 'Please pick an image you\'d like to use. Images should be around 1200 pixels wide or larger. The system will resize and compress these images for you to optimise for web.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5bc82cf4de3ee',
			'label' => 'Add link button?',
			'name' => 'add_link_button',
			'type' => 'true_false',
			'instructions' => 'Check this if you\'d like to include a button link at the end of the content area.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5bc82d47de3ef',
			'label' => 'Button text',
			'name' => 'button_text',
			'type' => 'text',
			'instructions' => 'What words do you want to display on this button?',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5bc82cf4de3ee',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5bc82d97de3f0',
			'label' => 'Link URL',
			'name' => 'link_url',
			'type' => 'text',
			'instructions' => 'Where do you want the button to link to? 👨🏻‍🚀',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5bc82cf4de3ee',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5de38b2229079',
			'label' => 'Open in a new tab?',
			'name' => 'open_in_a_new_tab',
			'type' => 'true_false',
			'instructions' => 'Check this if you want the link to open in a new tab.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5bc82cf4de3ee',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
	],
	'min' => '',
	'max' => '',
];
$layouts['5bc830d66200e'] = [
	'key' => '5bc830d66200e',
	'name' => 'block-links',
	'label' => 'Block Links',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e555f8414f5a',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e9ad2665efb3',
			'label' => 'Items Per Row',
			'name' => 'plotcms_items_per_row',
			'type' => 'range',
			'instructions' => 'How many block links would you like to display per row on desktop screens?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => 3,
			'min' => 2,
			'max' => 4,
			'step' => '',
			'prepend' => '',
			'append' => '',
		],
		[
			'key' => 'field_5c8113af6ceff',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'An optional heading for this segment',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaea9d241077',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'Include a small intro before your block links.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5de3a3f76b177',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => 'An optional introductory section for your block links.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaea9d241077',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5bc830de6200f',
			'label' => 'Block',
			'name' => 'block',
			'type' => 'repeater',
			'instructions' => 'Add as many link blocks as you\'d like.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 1,
			'max' => 12,
			'layout' => 'block',
			'button_label' => 'Add Block Link',
			'sub_fields' => [
				[
					'key' => 'field_5bc8311162010',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => 'What text do you want to show up on this block link? ✍🏼',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				],
				[
					'key' => 'field_5bc8311b62011',
					'label' => 'Link URL',
					'name' => 'link_url',
					'type' => 'text',
					'instructions' => 'Paste in a URL where you would like this Block Link to go to.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				],
				[
					'key' => 'field_5bc8313a62012',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'Please pick an image that will be used for this block element. Pick something at least 1500px wide. We\'ll resize and compress so it\'s ace for the internet.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => 'plotBlockLinkPreview plotBlockLinkPreview--blockLink',
						'id' => '',
					],
					'hide_admin' => 0,
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				],
				[
					'key' => 'field_5c895cb86a9d3',
					'label' => 'Brightness',
					'name' => 'brightness',
					'type' => 'range',
					'instructions' => 'You might want to dim this image so the text can be read over the top of it. 0 is completely transparent, and 100 is completely visible. Slide away.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => 'plotBlockLinkPreview plotBlockLinkSlider plotBlockLinkSlider--blockLink',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => 100,
					'min' => '',
					'max' => 100,
					'step' => 1,
					'prepend' => '',
					'append' => '',
				],
			],
		],
	],
	'min' => '',
	'max' => '',
];
$layouts['5bc83c0bc1939'] = [
	'key' => '5bc83c0bc1939',
	'name' => 'faqs',
	'label' => 'FAQs',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5eaeaeab9013b',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5c8926ac26fdf',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'This is an optional heading for this Plot Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaeae2d09cc3',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'Include a small intro before your FAQs.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5de3f9347561d',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaeae2d09cc3',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5bc83c13c193a',
			'label' => 'FAQs to Display',
			'name' => 'faqs_to_display',
			'type' => 'repeater',
			'instructions' => 'If you haven\'t added any FAQs yet, or need to add more, head to FAQs in the main menu.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add FAQ',
			'sub_fields' => [
				[
					'key' => 'field_5de3fb9d8e513',
					'label' => 'FAQ',
					'name' => 'faq',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'post_type' => [
						0 => 'faq',
					],
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				],
			],
		],
	],
	'min' => '',
	'max' => '',
];
$layouts['5be9754d3df4a'] = [
	'key' => '5be9754d3df4a',
	'name' => 'carousel',
	'label' => 'Carousel',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e5bf68a7b985',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5de407a51775a',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'This is an optional heading for this Plot Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaeafdb787b2',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'Include a small intro before your carousel.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5de407ad1775b',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaeafdb787b2',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5ea1af726e82c',
			'label' => 'Carousel Type',
			'name' => 'carousel_type',
			'type' => 'select',
			'instructions' => 'The simple image carousel allows you to add a sliding image gallery. 🖼
A block link carousel lets you put in a sliding collection of big image links 👍',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'image' => 'Simple Image Carousel',
				'links' => 'Block Link Carousel',
			],
			'default_value' => [
				0 => 'image',
			],
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		],
		[
			'key' => 'field_5be975583df4b',
			'label' => 'Block Links',
			'name' => 'block_links',
			'type' => 'repeater',
			'instructions' => 'You can add between 3-6 block links for use in your carousel. They can have video or imagery in the background, text and buttons. All up to you. 🙌',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5ea1af726e82c',
						'operator' => '==',
						'value' => 'links',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'collapsed' => '',
			'min' => 3,
			'max' => 6,
			'layout' => 'block',
			'button_label' => 'Add Link',
			'sub_fields' => [
				[
					'key' => 'field_5beaaa48a1110',
					'label' => 'Slide Type',
					'name' => 'slide_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'choices' => [
						'image' => 'Image',
						'video' => 'Video',
					],
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => 'image',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				],
				[
					'key' => 'field_5be9756b3df4c',
					'label' => 'Background Image',
					'name' => 'background_image',
					'type' => 'image',
					'instructions' => 'Images should be around 2,500 pixels wide or larger.',
					'required' => 1,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5beaaa48a1110',
								'operator' => '==',
								'value' => 'image',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => 'plotAcfHalf plotAcfHalf--withClear plotBlockLinkPreview plotBlockLinkPreview--carouselBlockLink',
						'id' => '',
					],
					'hide_admin' => 0,
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				],
				[
					'key' => 'field_5de4091cb2557',
					'label' => 'Small Screen Background Image',
					'name' => 'small_screen_background_image',
					'type' => 'image',
					'instructions' => 'Optional image for smaller screens like phones. At least 1,200px wide.',
					'required' => 0,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5beaaa48a1110',
								'operator' => '==',
								'value' => 'image',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => 'plotAcfHalf plotBlockLinkPreview plotBlockLinkPreview--carouselBlockLink plotBlockLinkPreview--carouselBlockLink--smallScreen',
						'id' => '',
					],
					'hide_admin' => 0,
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				],
				[
					'key' => 'field_5beaaad0a1111',
					'label' => 'Background Video',
					'name' => 'background_video',
					'type' => 'file',
					'instructions' => 'Upload an mp4 to use as a background video. Make sure it doesn\'t have audio! And also keep the filesize down by compressing for web. Smaller the better please 🙏',
					'required' => 1,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5beaaa48a1110',
								'operator' => '==',
								'value' => 'video',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				],
				[
					'key' => 'field_5de40949b2558',
					'label' => 'Small Screen Background Video',
					'name' => 'small_screen_background_video',
					'type' => 'file',
					'instructions' => 'An optional video to render for small screens. Can be 640px wide, smaller the better in file size to keep things great and fast to load. Otherwise it\'ll load the main video.',
					'required' => 0,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5beaaa48a1110',
								'operator' => '==',
								'value' => 'video',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				],
				[
					'key' => 'field_5de40fdaf511f',
					'label' => 'Brightness',
					'name' => 'brightness',
					'type' => 'range',
					'instructions' => 'You might want to change the brightness of the background so that the text can be read over the top. 0 is completely transparent, and 100 is completely visible. Slide away 🍔',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => 'plotBlockLinkSlider plotBlockLinkSlider--carouselBlockLink',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => 100,
					'min' => '',
					'max' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				],
				[
					'key' => 'field_5be9759d3df4d',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Add a title for this block link.',
					'required' => 1,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5ea1a88fb7f79',
								'operator' => '==',
								'value' => '1',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				],
				[
					'key' => 'field_5eaed53cb50aa',
					'label' => 'Add some content?',
					'name' => 'add_some_content',
					'type' => 'true_false',
					'instructions' => 'Add in a small amount of text under the title if you want.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				],
				[
					'key' => 'field_5be975ab3df4e',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => 'You can add some optional content here. Leave blank if you don\'t want any.',
					'required' => 0,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5eaed53cb50aa',
								'operator' => '==',
								'value' => '1',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				],
				[
					'key' => 'field_5be975dc3df50',
					'label' => 'Link URL',
					'name' => 'link_url',
					'type' => 'text',
					'instructions' => 'Where do you want this block link to go to?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				],
				[
					'key' => 'field_5ea1bf686e82d',
					'label' => 'Add a button?',
					'name' => 'add_a_button',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				],
				[
					'key' => 'field_5be975bc3df4f',
					'label' => 'Button Text',
					'name' => 'button_text',
					'type' => 'text',
					'instructions' => 'Words to appear on your lovely button.',
					'required' => 1,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5ea1bf686e82d',
								'operator' => '==',
								'value' => '1',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				],
				[
					'key' => 'field_5de40ed3f511e',
					'label' => 'Open in a new tab?',
					'name' => 'open_in_a_new_tab',
					'type' => 'true_false',
					'instructions' => 'Check this if you want the link to open in a new tab.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				],
			],
		],
		[
			'key' => 'field_5ea1c5455b896',
			'label' => 'Images',
			'name' => 'images',
			'type' => 'repeater',
			'instructions' => 'You can add between 3-12 images for use in your carousel. 🦨',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5ea1af726e82c',
						'operator' => '==',
						'value' => 'image',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'collapsed' => '',
			'min' => 3,
			'max' => 12,
			'layout' => 'block',
			'button_label' => 'Add Another Image',
			'sub_fields' => [
				[
					'key' => 'field_5ea1c5455b898',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'Upload your image! As big as possible please.',
					'required' => 1,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5bbcd4e8cefd8',
								'operator' => '!=empty',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				],
			],
		],
	],
	'min' => '',
	'max' => '',
];

$layouts['layout_5e203df709f3f'] = [
	'key' => 'layout_5e203df709f3f',
	'name' => 'featured-artists',
	'label' => 'Featured Artists',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e5baaa37ee1b',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'standard' => 'Site Background Colour',
				'alternative' => 'Alternative Background Colour',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e203df709f40',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'Give a heading to this section if you\'d like.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaedbef18aff',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'If you\'d like a short bit of content before the artist blocks.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e203df709f41',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => 'Add a little introduction to this section if you\'d like. Leave it blank if you want too.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaedbef18aff',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5e203df709f42',
			'label' => 'Artists',
			'name' => 'artists',
			'type' => 'repeater',
			'instructions' => 'Please add in as many artists as you\'d like to feature',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 2,
			'max' => 9,
			'layout' => 'table',
			'button_label' => 'Add Artist',
			'sub_fields' => [
				[
					'key' => 'field_5e203e3c09f44',
					'label' => 'Artist',
					'name' => 'artist',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'post_type' => [
						0 => 'artist',
					],
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
				],
			],
		],
		[
			'key' => 'field_5e20482af0c9a',
			'label' => 'Add a button?',
			'name' => 'add_a_button',
			'type' => 'true_false',
			'instructions' => 'You can add a button at the bottom of this section. Typically a "view all artists" button. But can be anything you\'d like! 🎰',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e20484ff0c9b',
			'label' => 'Button Link',
			'name' => 'button_link',
			'type' => 'text',
			'instructions' => 'Paste in a link for you lovely button.',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e20482af0c9a',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e20486df0c9c',
			'label' => 'Button Text',
			'name' => 'button_text',
			'type' => 'text',
			'instructions' => 'What text do you want on the button?',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e20482af0c9a',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
	],
	'min' => '',
	'max' => '',
];
$layouts['layout_5e4471598c7bb'] = [
	'key' => 'layout_5e4471598c7bb',
	'name' => 'text-lineup',
	'label' => 'Text Lineup',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e4471fe8c7bf',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'An optional heading for this lineup section.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e4471618c7bc',
			'label' => 'Tiers',
			'name' => 'tiers',
			'type' => 'repeater',
			'instructions' => 'Add in up to four tiers for your text lineup.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'collapsed' => '',
			'min' => 1,
			'max' => 4,
			'layout' => 'block',
			'button_label' => 'Add Tier',
			'sub_fields' => [
				[
					'key' => 'field_5e74b8396ad7b',
					'label' => 'Allow artists to text wrap',
					'name' => 'allow_artists_to_text_wrap',
					'type' => 'true_false',
					'instructions' => 'Ticking this will allow artist names to spill on to the next line. Can be useful to keep things looking compact.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				],
				[
					'key' => 'field_5e44717b8c7bd',
					'label' => 'Artists',
					'name' => 'artists',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'collapsed' => '',
					'min' => 1,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add artist',
					'sub_fields' => [
						[
							'key' => 'field_5e4471858c7be',
							'label' => 'Artist',
							'name' => 'artist',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'post_type' => [
								0 => 'artist',
							],
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						],
					],
				],
				[
					'key' => 'field_5e455550658fb',
					'label' => 'Separator',
					'name' => 'separator',
					'type' => 'select',
					'instructions' => 'Pick the symbol that shows up between each artist in this tier.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'choices' => [
						'none' => 'None',
						',' => 'Comma',
						'•' => 'Bullet',
						'★' => 'Star',
						'|' => 'Pipe',
					],
					'default_value' => [
					],
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				],
			],
		],
		[
			'key' => 'field_5e4555dd658fc',
			'label' => 'End text',
			'name' => 'end_text',
			'type' => 'text',
			'instructions' => 'Optional text that appears after the artist listings.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '+ many more.',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e467cd7f2da8',
			'label' => 'Add Button?',
			'name' => 'add_button',
			'type' => 'true_false',
			'instructions' => 'If you\'d like a button at the end of this layout, add it here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e467ce8f2da9',
			'label' => 'Button Text',
			'name' => 'button_text',
			'type' => 'text',
			'instructions' => 'Text to appear on the button',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e467cd7f2da8',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e467d02f2daa',
			'label' => 'Button Link',
			'name' => 'button_link',
			'type' => 'text',
			'instructions' => 'Where do you want this button to link to?',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e467cd7f2da8',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
	],
	'min' => '',
	'max' => '',
];

$layouts['5beaae7f7e7ce'] = [
	'key' => '5beaae7f7e7ce',
	'name' => 'latest-articles',
	'label' => 'Latest Articles',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e4b0e85cfb95',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5de68e6e3734e',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'This is an optional heading for your latest articles Plot Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaedb1e275e0',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'If you\'d like a short bit of content before the articles.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5beaaf217e7d0',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaedb1e275e0',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5de68f163734f',
			'label' => 'Which articles to show?',
			'name' => 'which_articles_to_show',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'latest' => 'Show the latest articles automatically',
				'custom' => 'Let me pick which articles show up',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'latest',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5de6906678f47',
			'label' => 'Articles',
			'name' => 'articles',
			'type' => 'repeater',
			'instructions' => 'Pick which articles you want to show here!',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5de68f163734f',
						'operator' => '==',
						'value' => 'custom',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 3,
			'max' => 5,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => [
				[
					'key' => 'field_5de6907f78f48',
					'label' => 'Article',
					'name' => 'article',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'post_type' => [
						0 => 'post',
					],
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
				],
			],
		],
		[
			'key' => 'field_5e4b091c0a3c8',
			'label' => 'How many?',
			'name' => 'article_count',
			'type' => 'range',
			'instructions' => 'How many articles do you want to show?',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5de68f163734f',
						'operator' => '==',
						'value' => 'latest',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 3,
			'min' => 2,
			'max' => 4,
			'step' => '',
			'prepend' => '',
			'append' => '',
		],
		[
			'key' => 'field_5e5bb92daf6c1',
			'label' => 'Add a button?',
			'name' => 'add_a_button',
			'type' => 'true_false',
			'instructions' => 'You can add a button at the bottom of this section. Typically a "view all artists" button. But can be anything you\'d like! 🎰',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e5bb950af6c2',
			'label' => 'Button Text',
			'name' => 'button_text',
			'type' => 'text',
			'instructions' => 'What would you like written on the button?',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e5bb92daf6c1',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5e5bb96baf6c3',
			'label' => 'Button Link',
			'name' => 'button_link',
			'type' => 'text',
			'instructions' => 'Paste in a link where you\'d like this button to head. Most likely to the articles page.',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e5bb92daf6c1',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
	],
	'min' => '',
	'max' => '',
];
$layouts['layout_5c82487b7052f'] = [
	'key' => 'layout_5c82487b7052f',
	'name' => 'image-grid',
	'label' => 'Image Grid',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e5bf57282af3',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5de92578a279c',
			'label' => 'Grid Layout',
			'name' => 'grid_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				1 => 'Layout 1',
				2 => 'Layout 2',
				3 => 'Layout 3',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 1,
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5c892476eebbc',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'This is an optional heading for this Plot Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaee13a51a7b',
			'label' => 'Include an introduction',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'Put a small amount of text before your image grid.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5de7dbe6c6c7c',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => 'If you would like to include some content before the latest articles links, feel free to add here. 🐕',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaee13a51a7b',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5de7dc4cc6c7d',
			'label' => 'Images',
			'name' => 'images',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 7,
			'max' => 7,
			'layout' => 'table',
			'button_label' => 'Add Gallery Item',
			'sub_fields' => [
				[
					'key' => 'field_5de7dc73c6c7e',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'At least 1,600px wide please. We\'ll resize down and squash.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				],
				[
					'key' => 'field_5de7dcc5c6c80',
					'label' => 'Pop open a video',
					'name' => 'pop_open_a_video',
					'type' => 'file',
					'instructions' => 'Do you want this gallery item to pop open to a video? Add a video file if you do. Leave blank if you don\'t.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				],
			],
		],
	],
	'min' => '',
	'max' => '',
];

$layouts['layout_5df90424616e0'] = [
	'key' => 'layout_5df90424616e0',
	'name' => 'image-tiles',
	'label' => 'Image Tiles',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e5bf5af82af4',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5df90424616e2',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'This is an optional heading for this Plot Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaee83db20ef',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'A small bit of content before your image tiles.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5df90424616e3',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaee83db20ef',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5df90424616e4',
			'label' => 'Image Rows',
			'name' => 'image-rows',
			'type' => 'repeater',
			'instructions' => 'Each Image row consists of two images side by side. You can add up to 8 images 🎖',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'collapsed' => '',
			'min' => 1,
			'max' => 4,
			'layout' => 'block',
			'button_label' => 'Add Image Row',
			'sub_fields' => [
				[
					'key' => 'field_5df90424616e5',
					'label' => 'Image 1',
					'name' => 'image-1',
					'type' => 'image',
					'instructions' => 'At least 1,600px wide please. We\'ll resize down and squash.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				],
				[
					'key' => 'field_5e204bc6136df',
					'label' => 'Pop open a video',
					'name' => 'pop_open_a_video-1',
					'type' => 'file',
					'instructions' => 'Do you want this image to pop open to a video? Add a video file if you do. Leave blank if you don\'t.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				],
				[
					'key' => 'field_5e204ba1136de',
					'label' => 'Image 2',
					'name' => 'image-2',
					'type' => 'image',
					'instructions' => 'At least 1,600px wide please. We\'ll resize down and squash.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				],
				[
					'key' => 'field_5df90424616e6',
					'label' => 'Pop open a video',
					'name' => 'pop_open_a_video-2',
					'type' => 'file',
					'instructions' => 'Do you want this image to pop open to a video? Add a video file if you do. Leave blank if you don\'t.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				],
			],
		],
	],
	'min' => '',
	'max' => '',
];
$layouts['layout_5e8c61d881f71'] = [
	'key' => 'layout_5e8c61d881f71',
	'name' => 'embed-media',
	'label' => 'Embed Media',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e8c61d881f72',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'Remember! Your colour palettes can be set in the site Customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Standard Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
		],
		[
			'key' => 'field_5e8c61d881f73',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'This is an optional heading for this Plot Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaee93e26b1c',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'A small bit of content before your embed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e8c61d881f74',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaee93e26b1c',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5e8c61ee81f7a',
			'label' => 'Embed',
			'name' => 'embed',
			'type' => 'oembed',
			'instructions' => 'It\'s super easy to embed media from almost all popular websites. Paste in the URL and we\'ll work out how to display it. Can use: Facebook, Youtube, Vimeo, Spotify, Soundcloud and many more. Give it a go.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'width' => '',
			'height' => '',
		],
	],
	'min' => '',
	'max' => '',
];

$layouts['layout_5d9f3b3dadcd0'] = [
	'key' => 'layout_5d9f3b3dadcd0',
	'name' => 'form',
	'label' => 'Form',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e8a0bf381fab',
			'label' => 'Colour Scheme',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'This is the colour scheme of this Plot Layout. Remember! Your colour palettes can be set in the site Customizer. 🐕',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'plotAcfHalf',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Site Background Colour',
				'alternative' => 'Alternative Background Colour',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'alternative',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e8a0fc3083d9',
			'label' => 'Form Box Style',
			'name' => 'plotcms_form_box_style',
			'type' => 'radio',
			'instructions' => 'Your form colour and style options can be set in the customizer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'plotAcfHalf',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'standard' => 'Site Main Colour Scheme',
				'alternative' => 'Alternative Colour Scheme',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'solid',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5d9f3b4cadcd1',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => 'Give a heading to this section if you\'d like.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_5eaeed404b26f',
			'label' => 'Include an introduction?',
			'name' => 'include_an_introduction',
			'type' => 'true_false',
			'instructions' => 'A small bit of content before your form.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5d9f3b53adcd2',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaeed404b26f',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5d9f3b61adcd3',
			'label' => 'Form',
			'name' => 'form',
			'type' => 'post_object',
			'instructions' => 'Please pick a form to use for this module. You can create modules yourselves within the "forms" section of this admin area.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'post_type' => [
				0 => 'wpforms',
			],
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		],
		[
			'key' => 'field_5eaeedbec8d80',
			'label' => 'Add small print?',
			'name' => 'add_small_print',
			'type' => 'true_false',
			'instructions' => 'You can put a small bit of text, often a disclaimer, underneath this form.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5d9f3b9fadcd4',
			'label' => 'Small Print',
			'name' => 'small_print',
			'type' => 'wysiwyg',
			'instructions' => 'If you need any text underneath the form, you can add it here. Often a disclaimer or terms and conditions message is put here.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eaeedbec8d80',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
	],
	'min' => '',
	'max' => '',
];

$layouts['layout_5e584bf814f64'] = [
	'key' => 'layout_5e584bf814f64',
	'name' => 'separator',
	'label' => 'Separator',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_5e584bff14f65',
			'label' => 'Background Colour',
			'name' => 'plotcms_color_scheme',
			'type' => 'radio',
			'instructions' => 'This is the background colour beyond and around your separator. Remember! Your colour palettes can be set in the site Customizer. 🐕',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'standard' => 'Site Background Colour',
				'alternative' => 'Alternative Background Colour',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e584c5614f66',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => 'What image would you like to use as a separator?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		],
		[
			'key' => 'field_5e584c7914f67',
			'label' => 'Type',
			'name' => 'type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'plotAcfHalf',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'single' => 'Single image centered',
				'repeated' => 'Repeating pattern horizontally',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e584ce914f68',
			'label' => 'Width',
			'name' => 'width',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'plotAcfHalf',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'fullWidth' => 'As wide as the screen allows',
				'maxWidth' => 'As wide as your site\'s maximum width',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e584d3714f69',
			'label' => 'Height',
			'name' => 'height',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 40,
			'min' => 1,
			'max' => 200,
			'step' => '',
			'prepend' => '',
			'append' => 'pixels',
		],
		[
			'key' => 'field_5e584d8714f6a',
			'label' => 'Animation',
			'name' => 'animation',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e584ce914f68',
						'operator' => '==',
						'value' => 'fullWidth',
					],
					[
						'field' => 'field_5e584c7914f67',
						'operator' => '==',
						'value' => 'repeated',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'none' => 'No animation',
				'moveLeft' => 'Move from right to left',
				'moveRight' => 'Move from left to right',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'none',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
	],
	'min' => '',
	'max' => '',
];


if(get_field('performance_pages','option'))
	$layouts['featured_performances_layout'] = plotLayoutFeaturedPerformances();

acf_add_local_field_group([
	'key' => 'group_5bbcd4e374067',
	'title' => 'Plot Page Designer',
	'fields' => [
		[
			'key' => 'field_5bbcd4e8cefd8',
			'label' => 'Plot Layouts',
			'name' => 'plot_layouts',
			'type' => 'flexible_content',
			'instructions' => 'Add in as many custom Plot Layouts as you wish. You can drag and drop your segments to have complete control of your pages. 👍',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'plotSegmentsWrap',
				'id' => '',
			],
			'hide_admin' => 0,
			'layouts' => $layouts,
			'button_label' => 'Add a Plot Layout',
			'min' => '',
			'max' => '',
		],
	],
	'location' => $locations,
	'menu_order' => 14,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => [
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	],
	'active' => true,
	'description' => 'Our main flexible content page designer including all Plot Layouts.',
]);