<?php

acf_add_local_field_group([
	'key' => 'group_5e668d87bfa41',
	'title' => 'Listings Options',
	'fields' => [
		[
			'key' => 'field_5e668d8ec247d',
			'label' => 'Listings Type',
			'name' => 'listings_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				'auto' => 'Automatically populate in performance time order',
				'manual' => 'Manually add in listings in an order of my choice',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'auto',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e778b4ca6f22',
			'label' => 'Split by day?',
			'name' => 'split_by_day',
			'type' => 'true_false',
			'instructions' => 'Select this if you want your stage listings to be split by each day of your event.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e668d8ec247d',
						'operator' => '==',
						'value' => 'manual',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e668fb524992',
			'label' => 'Listings Style',
			'name' => 'listings_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'text' => 'List by performance title',
				'image' => 'List with performance imagery and title',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'text',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e7906448f9c9',
			'label' => 'Desktop Columns',
			'name' => 'desktop_columns_image',
			'type' => 'radio',
			'instructions' => 'How many artists do you want to display per row on desktop? On phones we\'ll stack one by one anyway.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e668fb524992',
						'operator' => '==',
						'value' => 'image',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'choices' => [
				3 => 'Three per row',
				4 => 'Four per row',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 3,
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e9604b20f87c',
			'label' => 'Desktop Columns',
			'name' => 'desktop_columns_text',
			'type' => 'range',
			'instructions' => 'How many stages do you want to show per row on desktop?',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e668fb524992',
						'operator' => '==',
						'value' => 'text',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'min' => 2,
			'max' => 3,
			'step' => '',
			'prepend' => '',
			'append' => '',
		],
		[
			'key' => 'field_5e668e10e8ab8',
			'label' => 'Listings by Day',
			'name' => 'listings_by_day',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e668d8ec247d',
						'operator' => '==',
						'value' => 'manual',
					],
					[
						'field' => 'field_5e778b4ca6f22',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add another day',
			'sub_fields' => [
				[
					'key' => 'field_5e668eb1e8ab9',
					'label' => 'Day',
					'name' => 'listings_day',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'choices' => [
						0 => 'Date not yet set',
						'01/07/2021' => 'Friday',
						'02/07/2021' => 'Saturday',
						'03/07/2021' => 'Sunday',
					],
					'default_value' => [
					],
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'array',
					'ajax' => 0,
					'placeholder' => '',
				],
				[
					'key' => 'field_5e668ecae8aba',
					'label' => 'Stages',
					'name' => 'stages',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'collapsed' => '',
					'min' => 1,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add Stage',
					'sub_fields' => [
						[
							'key' => 'field_5e669230861d3',
							'label' => 'Stage',
							'name' => 'stage',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'hide_admin' => 0,
							'post_type' => [
								0 => 'stage',
							],
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						],
						[
							'key' => 'field_5e66926260aa3',
							'label' => 'Performances',
							'name' => 'performances',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'collapsed' => '',
							'min' => 1,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Performance',
							'sub_fields' => [
								[
									'key' => 'field_5e66927d60aa4',
									'label' => 'Performance',
									'name' => 'performance',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => [
										'width' => '',
										'class' => '',
										'id' => '',
									],
									'post_type' => [
										0 => 'performance',
									],
									'taxonomy' => '',
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'ui' => 1,
								],
							],
						],
					],
				],
			],
		],
		[
			'key' => 'field_5e77a74fa6f24',
			'label' => 'Listings By Stage',
			'name' => 'listings_by_stage',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5e778b4ca6f22',
						'operator' => '!=',
						'value' => '1',
					],
					[
						'field' => 'field_5e668d8ec247d',
						'operator' => '!=',
						'value' => 'auto',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Stage',
			'sub_fields' => [
				[
					'key' => 'field_5e77a7ada6f25',
					'label' => 'Stage',
					'name' => 'stage',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'post_type' => [
						0 => 'stage',
					],
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				],
				[
					'key' => 'field_5e77a7c2a6f26',
					'label' => 'Performances',
					'name' => 'performances',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'collapsed' => '',
					'min' => 1,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Performance',
					'sub_fields' => [
						[
							'key' => 'field_5e77a7d0a6f27',
							'label' => 'Performance',
							'name' => 'performance',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'post_type' => [
								0 => 'performance',
							],
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						],
					],
				],
			],
		],
		[
			'key' => 'field_5e9591c670275',
			'label' => 'Show performance times',
			'name' => 'show_performance_times',
			'type' => 'true_false',
			'instructions' => 'Display performance times next to each listing.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e959ff4ab05f',
			'label' => 'Add Stage Descriptions',
			'name' => 'add_stage_descriptions',
			'type' => 'true_false',
			'instructions' => 'Stage descriptions can be added on your individual stage edit pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e95b439e9029',
			'label' => 'Add Stage Imagery',
			'name' => 'add_stage_imagery',
			'type' => 'true_false',
			'instructions' => 'Stage images can be added at the top of each listing.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e95fd31ea05a',
			'label' => 'Stage Read More Text',
			'name' => 'stage_read_more_text',
			'type' => 'text',
			'instructions' => 'Text for read more buttons that appear on your stage link sections.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => 'Read info',
			'placeholder' => 'Read info',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
	],
	'location' => [
		[
			[
				'param' => 'page',
				'operator' => '==',
				'value' => '992',
			],
		],
	],
	'menu_order' => 17,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
]);