<?php 

//This field group is only needed if stage pages are public.

if(get_field('stage_pages','option')) :

	acf_add_local_field_group([
		'key' => 'group_5ea09b45bbb22',
		'title' => 'Page Content',
		'fields' => [
			[
				'key' => 'field_5ea09b7322a0f',
				'label' => 'Information',
				'name' => 'information',
				'type' => 'repeater',
				'instructions' => 'Add as many pieces of info as you need.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => [
					[
						'key' => 'field_5ea09b9522a10',
						'label' => 'Info Title',
						'name' => 'info_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'hide_admin' => 0,
						'default_value' => '',
						'placeholder' => 'Opening hours',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5ea09bc122a11',
						'label' => 'Info',
						'name' => 'info',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'hide_admin' => 0,
						'default_value' => '',
						'placeholder' => '10:00- 02:00',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
				],
			],
			[
				'key' => 'field_5ea09d2cc6d28',
				'label' => 'Content',
				'name' => 'content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'hide_admin' => 0,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			],
		],
		'location' => [
			[
				[
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'stage',
				],
			],
		],
		'menu_order' => 4,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => [
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'revisions',
			5 => 'author',
			6 => 'format',
			7 => 'page_attributes',
			8 => 'featured_image',
			9 => 'categories',
			10 => 'tags',
			11 => 'send-trackbacks',
		],
		'active' => true,
		'description' => 'For Stages/ locations',
	]);

endif;