<?php

acf_add_local_field_group([
	'key' => 'group_5bf56bef31962',
	'title' => 'Tickets',
	'fields' => [
		[
			'key' => 'field_5bfaaa9a1953a',
			'label' => 'Hide Ticket Buttons',
			'name' => 'hide_ticket_buttons',
			'type' => 'true_false',
			'instructions' => 'Selecting this will hide the whole ticket button area. This is useful if you\'re not on sale yet, or if you want to display some Plot Layouts with information instead.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5eb4526df2a28',
			'label' => 'Add a tickets announcement',
			'name' => 'add_a_tickets_announcement',
			'type' => 'true_false',
			'instructions' => 'An announcement to sit above the tickets. Allows you to give a specific piece of advice or sales message to visitors.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_5e1dc269d76c7',
			'label' => 'Tickets Announcement',
			'name' => 'tickets_announcement',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_5eb4526df2a28',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		],
		[
			'key' => 'field_5e1dc2c9d76c8',
			'label' => 'Display Options',
			'name' => 'display_options',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'grid' => 'Display ticket options in boxes within a grid',
				'lines' => 'Display tickets in rows',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		],
		[
			'key' => 'field_5e1dc362d76c9',
			'label' => 'Tickets',
			'name' => 'tickets',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Ticket Group',
			'sub_fields' => [
				[
					'key' => 'field_5e1dc38dd76ca',
					'label' => 'Group Name',
					'name' => 'group_name',
					'type' => 'text',
					'instructions' => 'You can group your tickets together. A typical group name would be "Weekend" or "Friday Tickets"',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				],
				[
					'key' => 'field_5e9c20fe77776',
					'label' => 'Ticket items per row',
					'name' => 'desktop_rows',
					'type' => 'range',
					'instructions' => 'On desktop, how many ticket items do you want to show per row?',
					'required' => 0,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5e1dc2c9d76c8',
								'operator' => '==',
								'value' => 'grid',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'default_value' => 3,
					'min' => 2,
					'max' => 4,
					'step' => '',
					'prepend' => '',
					'append' => '',
				],
				[
					'key' => 'field_5e9c2b731b248',
					'label' => 'Ticket Text Position',
					'name' => 'ticket_text_position',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => [
						[
							[
								'field' => 'field_5e1dc2c9d76c8',
								'operator' => '==',
								'value' => 'grid',
							],
						],
					],
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'hide_admin' => 0,
					'choices' => [
						'over' => 'Put the title, price and button over the images',
						'below' => 'Put all text below the images',
					],
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => 'below',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				],
				[
					'key' => 'field_5e1dc3e5d76cb',
					'label' => 'Ticket Options',
					'name' => 'ticket_options',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'collapsed' => 'field_5e1dc3fad76cc',
					'min' => 1,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add ticket',
					'sub_fields' => [
						[
							'key' => 'field_5e1dc3fad76cc',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'hide_admin' => 0,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						],
						[
							'key' => 'field_5e1dc404d76cd',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'An image for this ticket option. At least 1200px wide please. 💀',
							'required' => 1,
							'conditional_logic' => [
								[
									[
										'field' => 'field_5e1dc2c9d76c8',
										'operator' => '==',
										'value' => 'grid',
									],
								],
							],
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'hide_admin' => 0,
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						],
						[
							'key' => 'field_5e1dc8bdb3917',
							'label' => 'Image Brightness',
							'name' => 'image_brightness',
							'type' => 'range',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => [
								[
									[
										'field' => 'field_5e1dc2c9d76c8',
										'operator' => '==',
										'value' => 'grid',
									],
									[
										'field' => 'field_5e9c2b731b248',
										'operator' => '!=',
										'value' => 'below',
									]
								],
							],
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'hide_admin' => 0,
							'default_value' => 100,
							'min' => 0,
							'max' => 100,
							'step' => '',
							'prepend' => '',
							'append' => '',
						],
						[
							'key' => 'field_5e1dc430d76ce',
							'label' => 'Subheading',
							'name' => 'subheading',
							'type' => 'text',
							'instructions' => 'Optional text to go underneath the title.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						],
						[
							'key' => 'field_5e1dc442d76cf',
							'label' => 'Price',
							'name' => 'price',
							'type' => 'text',
							'instructions' => 'The display price of this ticket.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'hide_admin' => 0,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						],
						[
							'key' => 'field_5e1dc45dd76d0',
							'label' => 'Ticket Link',
							'name' => 'url',
							'type' => 'text',
							'instructions' => 'Paste in the link for this ticket from your ticketing provider.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'hide_admin' => 0,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						],
						[
							'key' => 'field_5e1dc82d3ef35',
							'label' => 'Button text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => 'Text for the link button',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'hide_admin' => 0,
							'default_value' => 'Buy now',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						],
						[
							'key' => 'field_5e1dc473d76d1',
							'label' => 'Sold out',
							'name' => 'sold_out',
							'type' => 'true_false',
							'instructions' => 'If you\'d like to disable this ticket box with a sold out message, check this.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						],
					],
				],
			],
		],
	],
	'location' => [
		[
			[
				'param' => 'page',
				'operator' => '==',
				'value' => '398',
			],
		],
	],
	'menu_order' => 12,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => [
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'featured_image',
		9 => 'categories',
		10 => 'tags',
		11 => 'send-trackbacks',
	],
	'active' => true,
	'description' => 'Tickets page specific features',
]);